In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
url = '/content/drive/MyDrive/datasets/melb_data.csv'
df = pd.read_csv(url)

df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [4]:
df.nunique()

Suburb             314
Address          13378
Rooms                9
Type                 3
Price             2204
Method               5
SellerG            268
Date                58
Distance           202
Postcode           198
Bedroom2            12
Bathroom             9
Car                 11
Landsize          1448
BuildingArea       602
YearBuilt          144
CouncilArea         33
Lattitude         6503
Longtitude        7063
Regionname           8
Propertycount      311
dtype: int64

In [6]:
df.shape

(13580, 21)

In [7]:
cols_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount',
               'Distance', 'CouncilArea', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']

df = df[cols_to_use]
df.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,1.0,202.0,NaN,1480000.0
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,0.0,156.0,79.0,1035000.0
2,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,0.0,134.0,150.0,1465000.0
3,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,1.0,94.0,NaN,850000.0
4,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra,3.0,1.0,2.0,120.0,142.0,1600000.0

In [8]:
df.shape

(13580, 15)

In [9]:
df.isna().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          0
Propertycount       0
Distance            0
CouncilArea      1369
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
Price               0
dtype: int64

In [10]:
cols_to_fill_zero = ['Propertycount', 'Distance', 'Bathroom', 'Car']
df[cols_to_fill_zero] = df[cols_to_fill_zero].fillna(0)
df.isna().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          0
Propertycount       0
Distance            0
CouncilArea      1369
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea     6450
Price               0
dtype: int64

In [11]:
df['BuildingArea'] = df['BuildingArea'].fillna(df.BuildingArea.mean())
df.isna().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          0
Propertycount       0
Distance            0
CouncilArea      1369
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
Price               0
dtype: int64

In [16]:
df[df['CouncilArea'].isnull()]

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
7584,Brighton East,3,h,VB,Ray,Southern Metropolitan,6938.0,10.7,NaN,3.0,1.0,3.0,724.0,151.96765,1270000.0
10797,Reservoir,3,h,SP,Barry,Northern Metropolitan,21650.0,12.0,NaN,3.0,1.0,1.0,308.0,151.96765,526250.0
12213,Aberfeldie,4,h,S,Brad,Western Metropolitan,1543.0,7.5,NaN,4.0,3.0,3.0,511.0,187.00000,1436000.0
12214,Albion,5,h,S,hockingstuart,Western Metropolitan,2185.0,10.5,NaN,5.0,2.0,3.0,732.0,151.96765,905000.0
12215,Alphington,4,h,S,Love,Northern Metropolitan,2211.0,5.7,NaN,4.0,3.0,2.0,720.0,151.96765,1680000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,4,h,S,Barry,South-Eastern Metropolitan,7392.0,16.7,NaN,4.0,2.0,2.0,652.0,151.96765,1245000.0
13576,Williamstown,3,h,SP,Williams,Western Metropolitan,6380.0,6.8,NaN,3.0,2.0,2.0,333.0,133.00000,1031000.0
13577,Williamstown,3,h,S,Raine,Western Metropolitan,6380.0,6.8,NaN,3.0,2.0,4.0,436.0,151.96765,1170000.0
13578,Williamstown,4,h,PI,Sweeney,Western Metropolitan,6380.0,6.8,NaN,4.0,1.0,5.0,866.0,157.00000,2500000.0
13579,Yarraville,4,h,SP,Village,Western Metropolitan,6543.0,6.3,NaN,4.0,1.0,1.0,362.0,112.00000,1285000.0

In [17]:
df.shape

(13580, 15)

In [18]:
df.dropna(inplace=True)
df.isna().sum()

Suburb           0
Rooms            0
Type             0
Method           0
SellerG          0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
Price            0
dtype: int64

In [19]:
df.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,1.0,202.0,151.96765,1480000.0
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,2.0,1.0,0.0,156.0,79.00000,1035000.0
2,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,0.0,134.0,150.00000,1465000.0
3,Abbotsford,3,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra,3.0,2.0,1.0,94.0,151.96765,850000.0
4,Abbotsford,4,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra,3.0,1.0,2.0,120.0,142.00000,1600000.0

In [20]:
df = pd.get_dummies(df, drop_first=True)

In [21]:
df

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Aberfeldie,...,CouncilArea_Moreland,CouncilArea_Nillumbik,CouncilArea_Port Phillip,CouncilArea_Stonnington,CouncilArea_Unavailable,CouncilArea_Whitehorse,CouncilArea_Whittlesea,CouncilArea_Wyndham,CouncilArea_Yarra,CouncilArea_Yarra Ranges
0,2,4019.0,2.5,2.0,1.0,1.0,202.0,151.96765,1480000.0,0,...,0,0,0,0,0,0,0,0,1,0
1,2,4019.0,2.5,2.0,1.0,0.0,156.0,79.00000,1035000.0,0,...,0,0,0,0,0,0,0,0,1,0
2,3,4019.0,2.5,3.0,2.0,0.0,134.0,150.00000,1465000.0,0,...,0,0,0,0,0,0,0,0,1,0
3,3,4019.0,2.5,3.0,2.0,1.0,94.0,151.96765,850000.0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,4019.0,2.5,3.0,1.0,2.0,120.0,142.00000,1600000.0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12208,3,6380.0,6.8,3.0,1.0,0.0,296.0,151.96765,1285000.0,0,...,0,0,0,0,0,0,0,0,0,0
12209,2,4380.0,4.6,2.0,1.0,1.0,0.0,61.60000,560000.0,0,...,0,0,0,1,0,0,0,0,0,0
12210,3,2940.0,25.5,3.0,2.0,2.0,400.0,151.96765,525300.0,0,...,0,0,0,0,0,0,1,0,0,0
12211,2,6543.0,6.3,2.0,1.0,2.0,269.0,151.96765,750000.0,0,...,0,0,0,0,0,0,0,0,0,0
12212,6,6543.0,6.3,6.0,3.0,2.0,1087.0,388.50000,2450000.0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
X = df.drop('Price', axis=1)
y = df.Price

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)

In [24]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)

In [25]:
reg.score(X_test, y_test)

-58779444151.45507

In [26]:
reg.score(X_train, y_train)

0.7120927411008791

In [27]:
from sklearn import linear_model

lasso_reg = linear_model.Lasso(alpha=50, max_iter=100, tol=0.1)
lasso_reg.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.272e+14, tolerance: 3.475e+14
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=50, max_iter=100, tol=0.1)

In [31]:
lasso_reg.score(X_test, y_test)

0.6635378648697848

In [30]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=50, max_iter=100, tol=0.1)
ridge_reg.fit(X_train, y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [32]:
ridge_reg.score(X_train, y_train)

0.6767113841211122