In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

In [4]:
# Read the CSV file
csv_file_path = '/content/drive/MyDrive/datasets/titanic.csv'
df = pd.read_csv(csv_file_path)

# Perform operations on the dataframe
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis=1, inplace=True)

In [6]:
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [7]:
target=df.Survived
inputs=df.drop('Survived', axis=1)

In [10]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [11]:
inputs = pd.concat([inputs, dummies], axis=1)
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [14]:
inputs.isnull().sum()

Pclass      0
Sex         0
Age       177
Fare        0
female      0
male        0
dtype: int64

In [15]:
 inputs.Age = inputs.Age.fillna(inputs.Age.mean())
 inputs

     Pclass     Sex        Age     Fare  female  male
0         3    male  22.000000   7.2500       0     1
1         1  female  38.000000  71.2833       1     0
2         3  female  26.000000   7.9250       1     0
3         1  female  35.000000  53.1000       1     0
4         3    male  35.000000   8.0500       0     1
..      ...     ...        ...      ...     ...   ...
886       2    male  27.000000  13.0000       0     1
887       1  female  19.000000  30.0000       1     0
888       3  female  29.699118  23.4500       1     0
889       1    male  26.000000  30.0000       0     1
890       3    male  32.000000   7.7500       0     1

[891 rows x 6 columns]

In [16]:
inputs.isnull().sum()

Pclass    0
Sex       0
Age       0
Fare      0
female    0
male      0
dtype: int64

In [20]:
inputs.drop('Sex', axis=1, inplace=True)

In [21]:
inputs

     Pclass        Age     Fare  female  male
0         3  22.000000   7.2500       0     1
1         1  38.000000  71.2833       1     0
2         3  26.000000   7.9250       1     0
3         1  35.000000  53.1000       1     0
4         3  35.000000   8.0500       0     1
..      ...        ...      ...     ...   ...
886       2  27.000000  13.0000       0     1
887       1  19.000000  30.0000       1     0
888       3  29.699118  23.4500       1     0
889       1  26.000000  30.0000       0     1
890       3  32.000000   7.7500       0     1

[891 rows x 5 columns]

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2, random_state=42)

In [23]:
X_train.shape

(712, 5)

In [24]:
X_test.shape

(179, 5)

In [25]:
y_train.shape

(712,)

In [26]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [27]:
model.fit(X_train, y_train)

GaussianNB()

In [28]:
model.score(X_test, y_test)

0.776536312849162

In [29]:
X_test[:10]

     Pclass        Age     Fare  female  male
709       3  29.699118  15.2458       0     1
439       2  31.000000  10.5000       0     1
840       3  20.000000   7.9250       0     1
720       2   6.000000  33.0000       1     0
39        3  14.000000  11.2417       1     0
290       1  26.000000  78.8500       1     0
300       3  29.699118   7.7500       1     0
333       3  16.000000  18.0000       0     1
208       3  16.000000   7.7500       1     0
136       1  19.000000  26.2833       1     0

In [30]:
y_test[:10]

709    1
439    0
840    0
720    1
39     1
290    1
300    1
333    0
208    1
136    1
Name: Survived, dtype: int64

In [31]:
model.predict(X_test[:10])

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1])

In [33]:
model.predict_proba(X_test[:10])
# [not survived proba, survived proba]

array([[0.9906724 , 0.0093276 ],
       [0.98005615, 0.01994385],
       [0.98884743, 0.01115257],
       [0.01399093, 0.98600907],
       [0.04536928, 0.95463072],
       [0.00186328, 0.99813672],
       [0.06140727, 0.93859273],
       [0.98779422, 0.01220578],
       [0.04757714, 0.95242286],
       [0.00698675, 0.99301325]])